name: run subdomainAndPoc

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  scan-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Run subdomainAndPoc
        run: |
          python run.py

      - name: Compress subdomainAndPoc directory
        run: |
          rm -rf dddd
          ls -alh
          cd ..
          tar -czvf subdomainAndPoc.tar.gz subdomainAndPoc
          ls -alh
          mv subdomainAndPoc.tar.gz subdomainAndPoc
          cd subdomainAndPoc
          ls -alh

      - name: Upload compressed results
        uses: actions/upload-artifact@v4
        with:
          name: subdomainAndPoc
          path: subdomainAndPoc.tar.gz
          if-no-files-found: error
          retention-days: 7
          compression-level: 6
          overwrite: false
          include-hidden-files: false
    
